version: '3'


services:

  pooping_be:
    container_name: pooping_be
    image: chci-kakat:latest
    depends_on:
      - pooping_db
    ports:
      - "8080:8080"

  pooping_db:
    image: mariadb:latest
    container_name: pooping_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pooping
    ports:
      - "3306:3306"